### ISSUE TITLE
Menu items missing on 4k resolution

### ISSUE THREAD

**Issue by Patschke** [Torridity/dsworkbench#22]
Wenn ich DS-Workbench starte, während mein 4k Bildschirm angeschlossen ist, fehlen 3/5 der Menüs (es fehlen Ansicht, Sonstiges, sowie das runde-Axt-Menü). 

Der Fehler ist reproduzierbar, d.h. wenn ich den Bildschirm ausstecke startet Workbench wie gewohnt, stecke ich den Bildschirm anschließend ein, so bleiben auch alle Menüs vorhanden. Starte ich bei angeschlossenem Monitor, so fehlen die Menüs. Der Fehler bleibt bestehen, wenn ich Workbench auf einem anderen Monitor als dem angeschlossenen 4k Monitor starte (d.h. zwei Monitore glechzeitig betreibe). Ausschlag gebend ist die Konfiguration bei Start des Computers. 

System: 
OS: Windows 10
APU: AMD A10-7890K Radeon R7
Bildschirm: A0C U2879VF (DisplayPort 2)
Java: 1.8.0_111-b14

Der Fehler betrifft sowohl die letzte Release-Version (3.43), als auch den aktuellsten Entwicklungs-Build. 

Ich habe bislang keine Ahnung, was den Fehler verursachen könnte. 

HD: 
![hd](https://cloud.githubusercontent.com/assets/17853362/20074618/4634763c-a531-11e6-8f59-107bd3ca50a5.png)

4k: 
![4k](https://cloud.githubusercontent.com/assets/17853362/20074622/4a479a56-a531-11e6-8ddb-5bc25606d746.png)

**Comment by Patschke** [comment]
Ich würde assign: @Patschke schreiben, wenn ich das dürfte

**Comment by Torridity** [comment]
Hallo,

du kannst dich dem Problem gern annehmen, allerdings gibts da mindestens ein wesentliches Problem, aber dazu gleich. Der Fehler wurde bereits vor einiger Zeit im DS Forum diskutiert, schaut mal ab diesem Beitrag (danach kommen in Abständen noch ein paar Beiträge dazu): 

https://forum.die-staemme.de/index.php?threads/ds-workbench.80831/page-86#post-4092238

Deine Screenshots schauen so aus als wenn dort genau dasselbe Problem besteht, nämlich die zu hohe Schriftskalierung. Wenn du diese in deinem System reduzierst sollte das Menü sichtbar sein. 

Das Problem an einer saubereren Lösung ist hier, dass es vermutlich von Java selbst gelöst werden muss und Java und Windows offenbar zusammen ein >4K Problem haben. Meine Entwicklungsumgebung schaut unter Win 10 auch extrem bescheiden aus, ich hab mich damit aber noch nicht genauer befasst und daher keine Lösung. Programmatisch in DSWB wird man das Problem nicht ohne Weiteres gelöst bekommen denke ich, aber schau wie gesagt mal drauf, vllt. findest du eine Lösung.

**Comment by Patschke** [comment]
Es gibt tatsächlich einen java-Bug was high-dpi scaling angeht, allerdings sollte das eben nur die Skalierung betreffen. Es sollte alles mögliche winzig sein, aber trotzdem da sein - jedenfalls ist das die Art, wie ich den Bug verstehe.

**Comment by Torridity** [comment]
Das mag sein, allerdings könnte eben damit die Menüband-Komponente die ich in DSWB verwende Probleme haben, da diese dynamisch bestimmt, welche Icons angezeigt werden, wie groß diese sind und ab wann sie gruppiert werden. Leider habe ich zu der Komponente keinen Source Code und soweit ich weiß wurde das Projekt vor sehr langer Zeit eingestellt, so dass sich Probleme da nur sehr schwer beheben lassen.
