### ISSUE TITLE
Falsche moralanzeige auf der Map

### ISSUE THREAD

**Issue by extremeCrazyCoder** [Torridity/dsworkbench#26]
In der Tabelle auf der Map wird die Moral auf Welten, die nicht die "nicht zeitbasierte Moral" verwenden, falsch angezeigt.
Korrekte Berechnung siehe [https://help.die-staemme.de/wiki/Moral](https://help.die-staemme.de/wiki/Moral)

**Comment by Torridity** [comment]
Ja, die zeitbasierte Moral habe ich nie implementiert.
