### ISSUE TITLE
Taktikplaner - Auffüllen von Unterstützungen berechnet nicht korrekte Befehle

### ISSUE THREAD

**Issue by philippwinter** [Torridity/dsworkbench#27]
Wenn man viele Unterstützungen schickt, und insbesondere mit kleinen Splits, tendiert Workbench dazu nicht mehr korrekt über die übriggebliebenen Truppen im Dorf Bescheid zu wissen. Sind etwa 5000/4680 Speer/Speer vorhanden, kann es sein, dass dennoch 5 Befehle mit 1k/1k Splits erstellt werden.
Die genaue Fehlerursache dafür habe ich noch nicht gefunden, da ich den Code von SupportCalculator/SupportRefillCalculationPanel/BruteForce noch nicht ganz durchstiegen habe. Falls jemand einen Tip dazu hat, wäre das gerne gesehen. 

/phil

**Comment by extremeCrazyCoder** [comment]
Durch dieses Gebiet habe ich mich schon durchgekämpft :smile:
Das ist kein Fehler sondern ein Feature (in den Einstellungen bei Verteidigung kann die Toleranz für Einzelunterstützungen eingestellt werden, probier es mal die auf 0% zu setzen)
Falls du im ganzen Taktikplaner noch Fehler findest gib bitte bescheid, damit ich die Ausbessern kann (in den Code habe ich mich schon eingelesen).

**Comment by philippwinter** [comment]
Jap, die Einstellung habe ich auch gefunden gehabt. Ich finde die Entscheidung, als Standardwert etwas anderes als 0% einzustellen allerdings gewagt, insbesondere da sich kaum ein Nutzer darüber bewusst ist. Vielleicht kann man hier zumindest eine Anzeige der aktuellen Toleranz in dem Planungsfenster einbauen?
Alles klar, mache ich. Ein Punkt wäre da beispielsweise, dass in der abschließenden Übersicht (welche Befehle auf welches Dorf zugeteilt wurde) jedes Dorf doppelt genannt wird.

**Comment by extremeCrazyCoder** [comment]
Die Standardwerte sind immer wieder etwas gewagt (bei den Splits im Angriffsplaner ist er auch auf 10%) es wäre eine gute Idee die ein bisschen zu ändern

Den Fehler habe ich bereits ausgebessert (steht in meiner Pullrequest).

**Comment by extremeCrazyCoder** [comment]
Nachdem ich mir das mit den Default Values angesehen habe (sie ist in 3 verschiedenen Files an 6 Orten gespeichert) glaube ich, dass das ganze system mit den Defaults mal überarbeiten werde (ich denke da so an eine Klasse "GlobalDefaults.java" wo alle drinnen stehen

**Comment by philippwinter** [comment]
Auf jeden Fall, leider wird im gesamten Code vieles doppelt und dreifach gemacht, was uns jetzt das Optimieren etwas erschwert.

**Comment by Torridity** [comment]
Das sind gewachsene Strukturen und wer kann denn ahnen dass sich irgendwann mal jemand den Code anschaut. ;-) 

Ich finde es trotzdem gut dass ihr das macht...viel Spaß/Erfolg weiterhin.

**Comment by extremeCrazyCoder** [comment]
Ich habe jetzt die neue Klasse geschrieben.

Das sind alle Werte die über GlobalOptions  gespeichert werden:
`GLOBAL_DEFAULTS.addProperty("attack.movement", false);
GLOBAL_DEFAULTS.addProperty("attack.planer.check.amount", 20000);
GLOBAL_DEFAULTS.addProperty("attack.planer.enable.check", true);
GLOBAL_DEFAULTS.addProperty("attack.script.attacks.in.overview", true);
GLOBAL_DEFAULTS.addProperty("attack.script.attacks.in.place", true);
GLOBAL_DEFAULTS.addProperty("attack.script.attacks.in.village.info", true);
GLOBAL_DEFAULTS.addProperty("attack.script.attacks.on.confirm.page", true);
GLOBAL_DEFAULTS.addProperty("check.updates.on.startup", true);
GLOBAL_DEFAULTS.addProperty("church.frame.alwaysOnTop", false); //?correct
GLOBAL_DEFAULTS.addProperty("clipboard.notification", true);
GLOBAL_DEFAULTS.addProperty("clock.alwaysOnTop", false);
GLOBAL_DEFAULTS.addProperty("command.sleep.time", 150);
GLOBAL_DEFAULTS.addProperty("conquers.frame.alwaysOnTop", false); //?correct
GLOBAL_DEFAULTS.addProperty("default.browser", "");
GLOBAL_DEFAULTS.addProperty("default.mark", 0);
GLOBAL_DEFAULTS.addProperty("delete.farm.reports.on.exit", true);
GLOBAL_DEFAULTS.addProperty("draw.attacks.by.default", false);
GLOBAL_DEFAULTS.addProperty("extended.attack.vectors", false);
GLOBAL_DEFAULTS.addProperty("extended.text.attacks", false);
GLOBAL_DEFAULTS.addProperty("form.config.frame.alwaysOnTop", false);
GLOBAL_DEFAULTS.addProperty("half.ribbon.size", false);
GLOBAL_DEFAULTS.addProperty("highlight.tribes.villages", false);
GLOBAL_DEFAULTS.addProperty("include.support", true);
GLOBAL_DEFAULTS.addProperty("inform.on.updates", true);
GLOBAL_DEFAULTS.addProperty("layer.order", null); //?correct
GLOBAL_DEFAULTS.addProperty("main.size.height", Toolkit.getDefaultToolkit().getScreenSize().getWidth() - 50);
GLOBAL_DEFAULTS.addProperty("main.size.width", Toolkit.getDefaultToolkit().getScreenSize().getHeight() - 50);
GLOBAL_DEFAULTS.addProperty("map.marker.transparency", 80);
GLOBAL_DEFAULTS.addProperty("map.showcontinents", true);
GLOBAL_DEFAULTS.addProperty("mark.villages.on.minimap", true);
GLOBAL_DEFAULTS.addProperty("max.density.troops", 65000);
GLOBAL_DEFAULTS.addProperty("max.farm.space", 20000);
GLOBAL_DEFAULTS.addProperty("max.loss.ratio", 50);
GLOBAL_DEFAULTS.addProperty("max.sim.rounds", 500);
GLOBAL_DEFAULTS.addProperty("no.welcome", false);
GLOBAL_DEFAULTS.addProperty("notify.duration", 1);
GLOBAL_DEFAULTS.addProperty("obst.server", "");
GLOBAL_DEFAULTS.addProperty("proxySet", false);
GLOBAL_DEFAULTS.addProperty("proxyHost", "");
GLOBAL_DEFAULTS.addProperty("proxyPort", "8080");
GLOBAL_DEFAULTS.addProperty("proxyType", 0);
GLOBAL_DEFAULTS.addProperty("proxyUser", "");
GLOBAL_DEFAULTS.addProperty("proxyPassword", "");
GLOBAL_DEFAULTS.addProperty("radar.size", 1);
GLOBAL_DEFAULTS.addProperty("radar.size", 60); //min or hour???? different!!
GLOBAL_DEFAULTS.addProperty("red.width", 0);
GLOBAL_DEFAULTS.addProperty("red.height", 0);
GLOBAL_DEFAULTS.addProperty("report.server.port", 8080);
GLOBAL_DEFAULTS.addProperty("ribbon.minimized", false);
GLOBAL_DEFAULTS.addProperty("screen.dir", ".");
GLOBAL_DEFAULTS.addProperty("search.frame.alwaysOnTop", false); //?correct
GLOBAL_DEFAULTS.addProperty("show.barbarian", true);
GLOBAL_DEFAULTS.addProperty("show.live.countdown", true);
GLOBAL_DEFAULTS.addProperty("show.map.popup", true);
GLOBAL_DEFAULTS.addProperty("show.mouseover.info", false);
GLOBAL_DEFAULTS.addProperty("show.popup.conquers", true);
GLOBAL_DEFAULTS.addProperty("show.popup.farm.space", true);
GLOBAL_DEFAULTS.addProperty("show.popup.moral", true);
GLOBAL_DEFAULTS.addProperty("show.popup.ranks", true);
GLOBAL_DEFAULTS.addProperty("show.sectors", true);
GLOBAL_DEFAULTS.addProperty("show.ruler", true);
GLOBAL_DEFAULTS.addProperty("stats.frame.alwaysOnTop", false);
GLOBAL_DEFAULTS.addProperty("support.tolerance", 0);
GLOBAL_DEFAULTS.addProperty("systray.enabled", SystrayHelper.isSystraySupported());
GLOBAL_DEFAULTS.addProperty("tag.frame.menu.visible", true); //?correct
GLOBAL_DEFAULTS.addProperty("tag.frame.table.visibility", "true;true;true;false");
GLOBAL_DEFAULTS.addProperty("tap.height", 0);
GLOBAL_DEFAULTS.addProperty("tap.width", 0);
GLOBAL_DEFAULTS.addProperty("text.attacks.per.file", "10");
GLOBAL_DEFAULTS.addProperty("village.order", 0);
GLOBAL_DEFAULTS.addProperty("zip.text.attacks", false);

for (UnitHolder unit : DataHolder.getSingleton().getUnits()) {
    GLOBAL_DEFAULTS.addProperty(unit.getName() + ".color", "#ff0000");
}`


Bei den folgenden Einstellungen bin ich mir nicht sicher was ich verwenden soll:
GLOBAL_DEFAULTS.addProperty("attack.template.header")
GLOBAL_DEFAULTS.addProperty("attack.template.block");
GLOBAL_DEFAULTS.addProperty("attack.template.footer");
GLOBAL_DEFAULTS.addProperty("standard.off");
GLOBAL_DEFAULTS.addProperty("standard.defense.split");
GLOBAL_DEFAULTS.addProperty("default.server");
GLOBAL_DEFAULTS.addProperty("default.skin");
String serverUser = GlobalOptions.getProperty("player." + defaultServer);

Und hier bin ich mir nicht sicher welches Template ich verwenden soll (sind unterschiedlich):
GLOBAL_DEFAULTS.addProperty("attack.bbexport.template", de.tor.tribes.util.AttackToBBCodeFormater.STANDARD_TEMPLATE);
GLOBAL_DEFAULTS.addProperty("attack.bbexport.template", "%TYPE% von %ATTACKER% aus %SOURCE% mit %UNIT% auf %DEFENDER% in %TARGET% startet am [color=red]%SEND%[/color] und kommt am [color=green]%ARRIVE%[/color] an");

**Comment by extremeCrazyCoder** [comment]
Habt ihr noch irgendwelche Änderungswünsche?

**Comment by extremeCrazyCoder** [comment]
Ich habe das ganze jetzt mal Commited (27e35ed2cb470c6ac6b03187db614d4d3afb49b7) Änderungswünsche sind willkommen :smile:
Eine Pull request gibt es nachdem ich es getestet habe
