### ISSUE TITLE
Verbesserung des Energiebedarfs von DSWorkbench

### ISSUE THREAD

**Issue by philippwinter** [Torridity/dsworkbench#28]
Es scheinen viele Hintergrundthreads zu laufen, obwohl überhaupt keine Arbeit zu tun ist (zum Beispiel zum "lauschen" auf kopierte Übersichten). Außerdem habe ich das Gefühl, dass bspw. das Zeichnen der GUI auch passiert, ohne dass DSWorkbench überhaupt benutzt wird. So wirkt sich normalerweise die Benutzung nicht (noch) negativer auf die Akkulaufzeit aus, wie das im Hintergrund laufende Programm. 

Als Beispiel für den Impact: Bei meinem MacBook Pro (2016, 15 inch) senkt WB die Akkulaufzeit von 10 auf knapp 2 Stunden herab.

**Comment by extremeCrazyCoder** [comment]
Mit dem Zeichen habe ich mich noch nicht auseinandergesetzt dazu kann ich nix sagen

Zum Lauschen:
Jede Sekunde wird der Hash des Clipboards mit einem gespeicherten Hash verglichen und bei Bedarf (Änderung) durch die diversen Parser geschickt

**Comment by extremeCrazyCoder** [comment]
Irgendwas dürfte beim Hashen nicht Funtionieren. Bei mir führt er das Checken vom Clipboard jede Sekunde aus
[dsworkbench.log.txt](https://github.com/Torridity/dsworkbench/files/781736/dsworkbench.log.txt)

**Comment by Torridity** [comment]
Der Clipboardparser läuft in der Tat jede Sekunde, allerdings macht der nichts was solch einen Energiebedarf verursachen sollte. Eher tippe ich tatsächlich auf das GUI. Ich meine mich dunkel zu erinnern, dass ich das Zeichnen einstelle sobald das DS WB Fenster minimiert ist. Ist es nur im Hintergrund kann es durchaus sein, dass weiter gezeichnet wird.

Was man noch machen kann ist, dass man im DS WB die ganzen Schnick-Schnack Layers wie (Angriffe, Kirchenradien etc) in den Hintergrund verschiebt, also hinter die Kartenebene. Soweit ich mich erinnere wird die Kartenebene nur gezeichnet wenn man sie verschiebt, während andere Layers permanent neu gezeichnet werden.

**Comment by extremeCrazyCoder** [comment]
Der Clipboard Parser tut aber (zumindest bei mir) nicht was er soll.
Er braucht ziemlich lange für einen Durchlauf (alle Möglichkeiten durchprobieren) und macht dies auch jede Sekunde (nich wie geplant und bei Änderungen im Hash Wert)

**Comment by Torridity** [comment]
Nun ja, dass er komische Sachen macht bedeutet nicht dass er nicht das macht was er soll. ;-)

Wie lange das nun braucht alles durchzuprobieren (sofern er anspringt) hängt von vielen Faktoren ab. Du könntest mal im Einzelnen schauen, welcher Parser die meiste Zeit braucht und dann dort ansetzen. 

Die Frage ist dann noch, was denn für Daten in der Zwischenablage sind, wenn du unnormales Verhalten beobachtest. Ich kann mir vorstellen, dass in der Zwischenablage ne Menge Kram sein kann, der das Hashing fordert oder eben einen der Parser verwirrt.

**Comment by extremeCrazyCoder** [comment]
Danke für die Tipps bei Gelegenheit werde ich mir den ganzen Parser Code ansehen.
Einlesen in den Teil muss ich mich sowieso, weil ich einen Parser Programmieren will mit dem Befehle importiert werden können

**Comment by extremeCrazyCoder** [comment]
@philippwinter kannst du bitte schauen, ob das Energieproblem durch die aktuelle Pull request gelöst wurde?
