### ISSUE TITLE
Log4j Konfiguration wird nicht angewandt

### ISSUE THREAD

**Issue by philippwinter** [Torridity/dsworkbench#30]
Siehe #29

**Comment by extremeCrazyCoder** [comment]
Stimmt so nicht ganz. Nicht überall würde ich sagen. Mein log file war, als ich es jetzt angeschaut habe voller errors. (Der Truppenparser70 ist anscheinend auch nicht fehlerfrei :roll_eyes: )
Auch wenn man in den Debug Mode Wechselt wird korrekterweise alles dort hin geloggt

**Comment by philippwinter** [comment]
Ich erhalte keine Debug-Meldungen, auch wenn ich dies in meiner config so einstelle :/

**Comment by extremeCrazyCoder** [comment]
Ich habs aktiviert indem ich auf Sonstiges -> About -> Button Debug gegangen bin
2. Möglichkeit WB mit Parameter -d starten
Ich habe es jetzt gerade getestet funktioniert

**Comment by philippwinter** [comment]
Dann scheint ja die Log4j Konfiguration nicht berücksichtig zu werden ^^ Genau sowas sollte man eigentlich dort einstellen, nicht zusätzlich in der Application

**Comment by Torridity** [comment]
Da hast du vollkommen Recht, Problem ist nur dass DS WB vorrangig von Nicht-Programmierern verwendet wird denen man erklärt, wie man ein Terminal öffnet. Bei dieser Zielgruppe erschien es mir durchaus sinnvoll, das Logging per Button zu aktivieren. ;-) 

Dass die Konfiguration nicht mehr funktioniert ist natürlich doof. Der kritische Punkt ist wohl in der Klasse de.tor.tribes.ui.windows.DSWorkbenchSplashScreen in Zeile 499. Wenn kein Kommandozeilenswitch aktiv ist, wird der Root Logger auf ERROR gesetzt und überschreibt dadurch deine Einstellungen in der Konfig-Datei.
