### ISSUE TITLE
DS Workbench stürtzt immer wieder ab

### ISSUE THREAD

**Issue by extremeCrazyCoder** [Torridity/dsworkbench#32]
Wie auch in den Einstellungen beschrieben (als Warnung vor alternativen Browsern):
"Solltest du einen alternativen Browser verwenden wollen, achte unbedingt darauf, dass der Browser gestartet ist wenn du die Einstellungen testest. Ansonsten kann es dazu kommen, dass DS Workbench nicht mehr reagiert."
reagiert WB beim Tab öffnen nicht mehr. Es kann passieren (wenn der Browser auch ein bisschen hängt) dass WB dabei dann komplett abstützt. Ein beenden ist dann nur noch über das Killen des Prozesses möglich.

**Comment by extremeCrazyCoder** [comment]
das ist nur zur Info (und als Erinnerung für mich)
Debugging habe ich bisher noch nicht betrieben

**Comment by Torridity** [comment]
Ich vermute das Problem liegt in Zeile  219  in de.tor.tribes.util.BrowserCommandSender 
Da öffen ich den Browser per Runtime.exec und warte per p.waitFor(); auf das Beenden des Prozesses bzw. darauf, dass der Browser gestartet ist. Ohne das Warten bleibt der Prozess vermutlich nicht hängen, aber man erfährt auch nicht ob der Aufruf erfolgreich war. Das Problem war/ist mir bekannt aber eine gute  Lösung hab ich nie gefunden.

**Comment by extremeCrazyCoder** [comment]
Vielen Dank für die Info das ist schonmal ein super Anhaltspunkt.
Wenn ich dann wieder ein Bisschen mehr Zeit habe werde ich mir das mal ansehen

**Comment by extremeCrazyCoder** [comment]
close da gemerged
