### ISSUE TITLE
PHP Services auf Torridity.de

### ISSUE THREAD

**Issue by extremeCrazyCoder** [Torridity/dsworkbench#34]
Die auf torridity.de gehosteten php Seiten funktionieren (zumindest wenn ich sie über den Browser aufrufe) nicht (z.B. http://torridity.de/dsworkbench/luckView.php?luck=20)
Ich erhalte immer die Fehlerseite von Joomla.

@torridity Kannst du mir vielleicht den Code schicken?
Eventuell kann ich das in Java nachbauen.

**Comment by Torridity** [comment]
Die Scripte liegen auch nicht unter /dsorkbench/ sondern unter /tools/

**Comment by extremeCrazyCoder** [comment]
Dann stimmt der Java Code nicht

**Comment by Torridity** [comment]
Erledigt.
