### ISSUE TITLE
Wachturm Simulation

### ISSUE THREAD

**Issue by georgkrause** [Torridity/dsworkbench#37]
Es wäre voll cool wenn man über die Karte, ähnlich wie für die Kirchen, eine Wachturm Simulation machen könnte. Also man wählt einfach Dörfer aus in denen ein Wachturm mit stufe x steht und sieht dann die Umkreise auf der Karte.

**Comment by extremeCrazyCoder** [comment]
Klingt gut willst du das Implementieren, oder soll ich es machen?
Die notwendigen Änderungen dafür müssten sich eh in grenzen halten.

**Comment by georgkrause** [comment]
Ich werde bis inklusive Oktober keine Zeit dafür haben :(

**Comment by extremeCrazyCoder** [comment]
ok da es vermutlich eh fast nur copy paste sein wird übernehme ich das gerne :D

**Comment by extremeCrazyCoder** [comment]
Ich habe jetzt ein kleines Problem:
Derzeit wird der Radius mit der Markierungs-Farbe des dazugehörenden Dorfes gezeichnet (was das markieren von Gegnern erlaubt)
Wie soll markiert werden, wenn es Kirchen und Wachtürme auf derselben Welt gibt?
Das kann man dann nicht mehr auseinanderhalten. Irgendeine Idee?

Mein Vorschlag wäre das ganze für Wachtürme & Kirchen mit einem Muster auszustatten, sodass man die beiden wieder auseinander kennt.

**Comment by georgkrause** [comment]
Oder man kann jeweils eins immer verstecken, damit es nicht total unübersichtlich wird. 

Gibt es überhaupt Welten, auf denen beides aktiv ist?

**Comment by extremeCrazyCoder** [comment]
https://zz2.tribalwars.works Auf der Sandbox Welt ist beides Aktiv
sonst kenne ich auch keine Welt (ich meide Wachturm Welten aber auch generell)

Das mit dem ein-aus-schalten ist eine gute Idee die Einstellung würde ich unter der Minimap unterbringen. Ich würde trotzdem zum Zeichen der Kirchenlinien eine gepunktete Linie und zum Zeichen der Wachturmlinie eine strichlierte Linie nehmen, weil man so nicht in den Einstellungen nachschauen muss was gerade Eingenschalten ist, sondern es mit der nötigen Erfahrung immer gleich weiß.

Vermutlich hast du eh recht und es gibt keine normalen Welten auf denen beides aktiv ist. Ich bin da aber lieber immer vorsichtig, als dass ich im Nachhinein nochmal nachbessern muss aufgrund einer falschen Annahme.

P.S.: Die Wachturmradien bekommen einen eigenen Layer (wie die Kirchenradien jetzt auch schon)

**Comment by georgkrause** [comment]
ich finde deine Überlegungen sehr gut ;)

**Comment by extremeCrazyCoder** [comment]
![test](https://user-images.githubusercontent.com/25514433/29791688-1dc3d950-8c3e-11e7-90da-b27dbd299007.png)

So wird das dann aussehen

**Comment by extremeCrazyCoder** [comment]
Ist mit dem jetzigen Push erledigt und kann geschlossen werden
