### ISSUE TITLE
Truppen werden nicht aktualisiert

### ISSUE THREAD

**Issue by reto1985** [Torridity/dsworkbench#40]
Hallo zusammen

Bis anhin konnte ich die Truppen und Gruppen über ein Script im violentmonkey (opera) in der jeweiligen übersicht mit ctrl a ctrl c synchronisieren.

Gruppen funktioniert , Truppen bleiben jedoch leer

Weiss jemand was ich hier anders machen muss oder wo der fehler liegen kann?
Ich nutze version 3.5
besten dank

reto

**Comment by Patrick-TU-KL** [comment]
Hallo reto, 

vielen Dank erstmal für den Fehlerbericht!

Kannst du einmal posten, wie genau deine Zwischenablage aussieht? Also nachdem synchronisieren per Strg+a / Strg+c einmal per Strg+v hier einfügen. Dann können wir ggf sehen, woran sich der Parser verschluckt...

Viele Grüße

**Comment by reto1985** [comment]
Hallo
Danke für die schnelle antwort:
habe zwei files angehänt, grupen funktioniert bei mir so, um das truppen file geht es ja

besten dank
[wb gruppen.txt](https://github.com/Torridity/dsworkbench/files/1425250/wb.gruppen.txt)
[wb truppen.txt](https://github.com/Torridity/dsworkbench/files/1425251/wb.truppen.txt)

**Comment by extremeCrazyCoder** [comment]
sieht für mich so aus, als ob du auf einem CH server wärst

hast du schon die ch.parserprop angepasst? (siehe: https://forum.die-staemme.de/index.php?threads/ds-workbench.80831/page-95#post-4167225)

**Comment by reto1985** [comment]
ja ist ein ch server, super habe das ch file angepasst, geht wieder besten dank :)

**Comment by Patrick-TU-KL** [comment]
damit dann wohl close #40
