### ISSUE TITLE
Clipboard Import Defekt in Version 3.5

### ISSUE THREAD

**Issue by RalfJeppesen** [Torridity/dsworkbench#41]
Der Import via Clipboard funktioniert in der Version 3.5 nicht unter Windows 10. In der Version 3.45 funktioniert dieselbe Zwischenablage jedoch.

**Comment by extremeCrazyCoder** [comment]
Kanns sein, dass du einen CH server nutzt? (siehe #40)

**Comment by RalfJeppesen** [comment]
Ja ist eine nicht DE Welt. Hat sich also erledigt.
