### ISSUE TITLE
Angriffe/Fakes werden nicht alle berechnet

### ISSUE THREAD

**Issue by reto1985** [Torridity/dsworkbench#42]
Hallo zusammen
Bei Workbench Version 3.5 hatte ich schon öfters Problem um fakes/Angriffe zu planen

Wenn ich z.B auf CH38 fakes oder offs planen will, berechnet es mir nicht alle möglichen angriffe,
heute habe ich als Ankunftsdatum 30.12.2017 als Test genommen. auf vier Dörfer von 38 berechnet es nur eine von zwei angriffen die ich möchte.

Ist dieses Problem auch bei anderen bekannt?

Besten Dank 

Reto

**Comment by extremeCrazyCoder** [comment]
Generell kann ich nur sagen, es ist noch kein solcher Bug bekannt.

Für eine Analyse bräuchte ich genauere Infos(Logs im Debug mode, was hast du Eingestellt, usw...)

Da du aber auf CH spielst könnte es sein, dass die Truppen / Gruppen nicht eingelesen wurden (hast du das Überprüft?), da es da den Bug #40 gibt.

**Comment by reto1985** [comment]
Hallo Wie bekomme ich die logs aus dem wb?
Gruppen und Truppen werden eingelesen, habe die angriffe sogar ohne filterung ausprobiert, geht auch nicht, teilweise kann ich dann, drei viermal versuchen irgendwann wenn ich glück habe geht es dann

 

    extremeCrazyCoder <notifications@github.com> schrieb am 23:15 Dienstag, 12.Dezember 2017:
 

 Generell kann ich nur sagen, es ist noch kein solcher Bug bekannt.Für eine Analyse bräuchte ich genauere Infos(Logs im Debug mode, was hast du Eingestellt, usw...)Da du aber auf CH spielst könnte es sein, dass die Truppen / Gruppen nicht eingelesen wurden (hast du das Überprüft?), da es da den Bug #40 gibt.—

**Comment by extremeCrazyCoder** [comment]
Kannst du dir mal das Logfile (liegt im Ordner logs) ansehen und falls es was interessantes enthält es hier posten?

Sollte nix interessantes dabei sein (intessant sind immer errors / warnings, die von WB kommen) dann lösch es bitte. Um an die logginginfos zu kommen Startest du WB (nach dem Löschen, weil er sonst kein neues File erstellt) und klickst dann bitte auf Sonstiges dann About. Im Fenster  dass dann aufgeht gibts rechts unten einen Button Debug. Nach einem Klick darauf ist WB gleich viel gesprächiger :) .

Könntest du bitte auch zusammenschreiben, was du genau alles eingestellt hast (fixe / intervall Ankunftszeit, wie viele Dörfer du verwendest, etc) daraus sollte sich dann normalerweise auch schon der Fehler feststellen lassen. Das logfile brauch ich eigentlich nur relativ selten (ich fordere es auch eher ungern an, weil darin wirklich fast alle Infos enthalten sind).

**Comment by reto1985** [comment]
Habe mal eine Word Dokument zusammen gestellt wie ich es mache, bei der alten Version hat es so immer funktioniert

Das gleiche Problem habe ich auch auf dem zweiten Laptop
Mache ich irgend einen Fehler?

Besten Dank für die Bemühungen 

[dsworkbench.log](https://github.com/Torridity/dsworkbench/files/1556732/dsworkbench.log)
[Workbench Berechnungsproblem.pdf](https://github.com/Torridity/dsworkbench/files/1556747/Workbench.Berechnungsproblem.pdf)

**Comment by extremeCrazyCoder** [comment]
ich seh schon.... das ist das gleiche Problem, wie das was mir ein anderer für den UT planer gesagt hat.
Workaround nimm keine Fixe Ankunftszeit.
Warum ist das so?
Der Berechnungsalgorithmus schaut nur nach, ob man den Befehl generell schicken könnte. Wenn du dann auf weiter drückst werden dann den einzelnen Befehlen Zeiten zugeordnet, wodurch WB bei manchen draufkommt: "Da müssen mehr als 5 Befehle in der gleichen Sekunde geschickt werden"  (muss nicht die Zahl 5 sein) und alle Befehle die zu viel sind einfach ignoriert.

**Comment by reto1985** [comment]
Das heisst das verhalten ist völlig normal?
Für fakes stimmt es spielt eine fixe ankunftszeit keine rolle, für offs aber schon
komischerweise hat es mit der vorherigen version immer funktioniert...

danke für die antwort, werde nun die ankunftszeiten bei den berechneten angriffen manuell anpassen

**Comment by extremeCrazyCoder** [comment]
eigentlich schon, optimal wäre natürlich, wenn der Algorithmus das mitbekommen würde, vielleicht kommt das auch noch irgendwan.

manuelles anpassen der Zeiten wird dir nicht viel helfen, weil du das ja auch nicht raushen kannst (5 Offs / sec ist schon ziemlich viel)

wobei ich werde mir das ganze nochmal ansehen (nachdem die werte bei zugeteilten angriffen nicht stimmen, was zumindest ein Anzeigebug ist)
nachdem der Log ziemlich nichtssagend ist (da dürfte einiges Fehlen warum auch immer) wäre es super, wenn du den Inhalt der Textbox beim berechnen noch Posten könntest.

Nachdem du auch meinst, dass es früher nicht so war könnte es doch ein Bug sein

**Comment by reto1985** [comment]
Hoffe habe das richtige kopiert?
ich hatte bisher maximal zwei angriffe zur gleichenzeit nach der berechnungen nie mehr, auch bei dieser berechnung sind einmal zwei angriffe zur gleichen zeit, nicht mehr

[Berechnung.txt](https://github.com/Torridity/dsworkbench/files/1556858/Berechnung.txt)

**Comment by extremeCrazyCoder** [comment]
ja stimmt danke

**Comment by extremeCrazyCoder** [comment]
nachdem ich mir jetzt das ganze nochmal genauer angesehen habe bezweifle ich sogar, dass du jemals 2 Angriffe zur gleichen Zeit abschicken musstest (gleich bedeutet auf die ms gleich). Ich kenne den Code doch noch nicht so gut wie ich dachte....

Ich werde das ganze jetzt ein bisschen lockern erst mal damit solche Probleme in Zukunft nicht mehr auftreten (falls keine freie passende Zeit gefunden wird dann wird der Angriff einfach irgendwo rein gequetscht ohne Rücksicht auf die Zeit

**Comment by reto1985** [comment]
okey besten dank
Das heisst es gibt bald eine neue version zum herunterladen?
lg reto
 

    extremeCrazyCoder <notifications@github.com> schrieb am 17:47 Montag, 1.Januar 2018:
 

 nachdem ich mir jetzt das ganze nochmal genauer angesehen habe bezweifle ich sogar, dass du jemals 2 Angriffe zur gleichen Zeit abschicken musstest (gleich bedeutet auf die ms gleich). Ich kenne den Code doch noch nicht so gut wie ich dachte....Ich werde das ganze jetzt ein bisschen lockern erst mal damit solche Probleme in Zukunft nicht mehr auftreten (falls keine freie passende Zeit gefunden wird dann wird der Angriff einfach irgendwo rein gequetscht ohne Rücksicht auf die Zeit—

**Comment by extremeCrazyCoder** [comment]
eine neue Version wird es geben, aber ob es bald ist weiß ich nicht
ich werde die Änderungen im lauf der nächsten Woche comiten (dann könntest du dir die Source files runterladen und selber kompillieren).

Eine offizielle Version wird aber noch dauern, weil es noch einige Bugs gibt die ich vorher ausbessern muss, und das ganze dann von Torridity nochmal angeschaut wird (und getestet).

**Comment by extremeCrazyCoder** [comment]
Commit ist raus, soweit sieht alles aus als ob es gehen würde (hab nur kurz drüber geschaut)

**Comment by reto1985** [comment]
Hallo
Berechnen funktioniert soweit tip top
Eine weitere Frage, Truppen einlesen auf dem CH server sollte dies schon funktionieren oder muss man hierfür noch das ch file von der version 3.5 einfügen?
besten dank
 

    extremeCrazyCoder <notifications@github.com> schrieb am 14:11 Sonntag, 14.Januar 2018:
 

 Commit ist raus, soweit sieht alles aus als ob es gehen würde (hab nur kurz drüber geschaut)—

**Comment by extremeCrazyCoder** [comment]
das einlesen von Truppen & Gruppeninformationen sollte funktionieren.

Das ch gab es in V3.5 nur deshalb extra, weil es sich nicht ausgezahlt hat dafür eine neue Version zu machen, In den neueren Versionen 3.6 und 3.61 sind diese Änderungen schon enthalten.

Weiters ist es auch so, dass sich das Format der Parserfiles von V3.5 auf V3.6 nochmal minimal geändert hat (bei V3.5 musste immer ch,   bei den einzelnen Properties stehen. Das ist ab V3.6 nichtmehr so)
Daher wäre diese File ohne Anpassungen inkompaibel und die Imports würden nicht funktionieren (er hat als Fallback die fix implementierten de settings, die mit ch inkompatibel sind)

Sollten die Truppenimports nicht gehen dann schreib das Bitte. Ich bin aber derzeit eh dabei mir einen Acc auf Ch hochzuspielen damit ich ein bisschen Testen kann.

Hättest du lust mir vielleicht ein bisschen zu helfen bei den Ch übersetzungen? (es gibt spezialfälle die man nur bei großen Accs hat und so weit will ich eigentlich nicht spielen)

**Comment by reto1985** [comment]
Hallo
Also Truppeneinlesen habe ich nicht hingekriegt, Gruppen funktionieren einwandfrei
Kann dir gerne bei den ch übersetzungen helfen, (acc hat momentan 3.7mio)
lg reto
 

    extremeCrazyCoder <notifications@github.com> schrieb am 12:31 Freitag, 26.Januar 2018:
 

 das einlesen von Truppen & Gruppeninformationen sollte funktionieren.Das ch gab es in V3.5 nur deshalb extra, weil es sich nicht ausgezahlt hat dafür eine neue Version zu machen, In den neueren Versionen 3.6 und 3.61 sind diese Änderungen schon enthalten.Weiters ist es auch so, dass sich das Format der Parserfiles von V3.5 auf V3.6 nochmal minimal geändert hat (bei V3.5 musste immer ch, bei den einzelnen Properties stehen. Das ist ab V3.6 nichtmehr so)
Daher wäre diese File ohne Anpassungen inkompaibel und die Imports würden nicht funktionieren (er hat als Fallback die fix implementierten de settings, die mit ch inkompatibel sind)Sollten die Truppenimports nicht gehen dann schreib das Bitte. Ich bin aber derzeit eh dabei mir einen Acc auf Ch hochzuspielen damit ich ein bisschen Testen kann.Hättest du lust mir vielleicht ein bisschen zu helfen bei den Ch übersetzungen? (es gibt spezialfälle die man nur bei großen Accs hat und so weit will ich eigentlich nicht spielen)—

**Comment by extremeCrazyCoder** [comment]
Folgende sachen Bräuchte ich: (am besten als Copy-Paste geht auch, wenn du einfach die entsprechenden Texte kopierst)
Ein Bericht wo alle verschiednen Gebäude drinnen stehen (als Spy Infos)
Ein Bericht wo der Wall durch Rammen beschädigt wird
Ein Bericht wo der ein Gebäude durch Katas beschädigt wird
Ein Bericht einer Adelung, wo Truppen unterwegs waren
Ein Bericht einer Adelung, wo Truppen noch in anderen Dörfern stationiert waren

Generell mach einfach so viel wie du lust drauf hast. Am wichtigesten wäre der Bericht der Adelung mit stationierten Truppen in anderen Dörfern. Den rest würde ich auch so irgendwie hinbekommen. Du kannst auch (falls du solche Berichte hast) mehrere Punkte mit einem erledigen :)

Danke schonmal im vorraus. Durch deine Hilfe wird es dann auch für Schweizer möglich sein den Farmmanager zu benutzen :D

**Comment by extremeCrazyCoder** [comment]
kann es sein, dass du vielleich auf einer Spezial Welt spielst? (die URL fängt nicht mit chXX,staemme.ch an ; XX steht für den Server) da könntest du derzeit noch Probleme haben

**Comment by reto1985** [comment]
Hallo im Anhang die Berichte hoffe passt so
spiele auf ch w38 , hat runen dörfer sonst ist eigentlich nichts speziell :D
das wäre der link auf dem browser:
https://ch38.staemme.ch/game.php?village=434&screen=mail




 

    extremeCrazyCoder <notifications@github.com> schrieb am 23:55 Samstag, 27.Januar 2018:
 

 kann es sein, dass du vielleich auf einer Spezial Welt spielst? (die URL fängt nicht mit chXX,staemme.ch an ; XX steht für den Server) da könntest du derzeit noch Probleme haben—

**Comment by extremeCrazyCoder** [comment]
danke das passt so

komisch dass es bei dir mit den Truppen nicht klappt....
kannst du mal im log schauen ob da irgendwas von errors / warn steht? (Dazu sollte WB im Debug mode sein:
1. Möglichḱeit: Sonstiges -> About -> Button Debug
2. Möglichkeit WB mit Parameter -d starten)

**Comment by reto1985** [comment]
Sollte ich im Debugmode auch gruppen einlesen können? komischer weise macht er dann nichts,

Beim Gruppen einlesen bekomme ich das Feedback das es geklappt hat, beim Truppeneinlesen jedoch nicht.
Wenn ich dann im filter z.B 10 spys eingebe werden einfach alle dörfer auf rot gesetzt
Dies ist im logfile nach dem leeren des files wenn ich wb starte, habe jedoch wb auf drei verschiedenen pc s ausprobiert, bei allen das gleiche problem


[dsworkbench.log](https://github.com/Torridity/dsworkbench/files/1670636/dsworkbench.log)

**Comment by extremeCrazyCoder** [comment]
ich habs jetzt selber gerade ausprobiert (und bei mir gehts auch nicht...)
erstmal sorry das ich es nicht schon früher ausprobiert hab (dann hättest du dir das Debugging ersparrt.

In deinem Log steht zwar ein error, dabei geht es aber nur um das abspielen der Notification. Diese wird (ich musste selber erst noch nachsehen) in einem Eigenen Thread mit gutem error handling bearbeitet, wodurch sich dadurch keine Probleme ergeben sollten.

vom Log her wären diese Zeilen wichtig gewesen:

> 2018-01-28 11:17:49,605 - DEBUG - TroopsParser70       (de.tor.tribes.util.parser.TroopsParser70 [273]) - Processing village Barbarendorf (470|616) K64
2018-01-28 11:17:49,605 - DEBUG - TroopsParser70       (de.tor.tribes.util.parser.TroopsParser70 [273]) - Test line 'Barbarendorf (470|616) K64 	eigeni 	0	0	0	0	0	0	0	0	0	0	0	0	0		Befehl' for property 'eigeni'
2018-01-28 11:17:49,605 - DEBUG - TroopsParser70       (de.tor.tribes.util.parser.TroopsParser70 [273]) - Handle line 'Barbarendorf (470|616) K64 	eigeni 	0	0	0	0	0	0	0	0	0	0	0	0	0		Befehl' for property 'eigeni'
2018-01-28 11:17:49,605 - DEBUG - TroopsParser70       (de.tor.tribes.util.parser.TroopsParser70 [273]) - Getting units from line '0	0	0	0	0	0	0	0	0	0	0	0	0		Befehl'

daran sind nicht die eigentlichen log Zeilen interessant sondern, dass dannach nix mehr kommt. Das bedeutet also, dass der Units-Parser abstürtzt. Ich glaube jetzt erstmal nicht, dass das was mit den CH-Servern zu tun hat (sondern es müsste auch die DE-Server betreffen) und werde es mir mal ansehen.

Eventuell ist das das gleiche Problem, warum man bei Berichten derzeit keine Truppeninfos importieren kann.

**Comment by extremeCrazyCoder** [comment]
so ich hab das Problem jetzt analysiert und herausgefunden, dass es von einer schlechten Übersetzung und einer schlechten Programmierung kommt. Den Code hab ich ausgebessert. Hier das neue ch.parserprop file, mit dem der Truppenimport funktionieren sollte: (ich musste an die Dateiendung ein .txt dazuhängen, damit ich es auf github hochladen konnte) 
[ch.parserprop.txt](https://github.com/Torridity/dsworkbench/files/1671654/ch.parserprop.txt)



P.S.: ich hab mich vorhin geirrt: der Parser ist nicht abgestürtzt sondern einfach in einer endlos schleife hängen geblieben.

**Comment by reto1985** [comment]
ja funktioniert bei mir mit dem truppen einlesen so auch :)
danke dir vielmas :)
 

    extremeCrazyCoder <notifications@github.com> schrieb am 23:05 Sonntag, 28.Januar 2018:
 

 so ich hab das Problem jetzt analysiert und herausgefunden, dass es von einer schlechten Übersetzung und einer schlechten Programmierung kommt. Den Code hab ich ausgebessert. Hier das neue ch.parserprop file, mit dem der Truppenimport funktionieren sollte: (ich musste an die Dateiendung ein .txt dazuhängen, damit ich es auf github hochladen konnte)
ch.parserprop.txtP.S.: ich hab mich vorhin geirrt: der Parser ist nicht abgestürtzt sondern einfach in einer endlos schleife hängen geblieben.—

**Comment by extremeCrazyCoder** [comment]
@retro1985
Kann diese Issue geschlossen werden?

**Comment by reto1985** [comment]
kann geschlossen werden danke
 

    extremeCrazyCoder <notifications@github.com> schrieb am 17:50 Montag, 5.Februar 2018:
 

 @retro1985
Kann diese Issue geschlossen werden?—

**Comment by extremeCrazyCoder** [comment]
@Torridity bitte schließen
