### ISSUE TITLE
Registrierungsfehler

### ISSUE THREAD

**Issue by Cilko** [Torridity/dsworkbench#47]
Guten Abend,

habe nun wieder vor nach paar Jahren mit workbench zu arbeiten. Habe mir dementsprechend auch die aktuellste Version geladen. Allerdings ist es mir beim ersten Starten nicht möglich eine Registrierung für den workbench Account abzuschließen. Stattdessen wir mir nur angezeigt das es sich um einen unbekannten Fehler handelt und ich mich an einen Entwickler wenden soll. Hoffe hier Hilfe zu erhalten.

MfG

**Comment by extremeCrazyCoder** [comment]
ok nachdem du einige Zeit weg warst hat sich hier bei WB mittlerweile einiges geändert.
So etwas wie den WB-Account den es früher gab gibt es nicht mehr (seitdem dsworkbench.de abgeschaltet wurde)
Daher gleich mal die erste Frage:
Bist du dir sicher, dass du die [Aktuelle Version](https://github.com/Torridity/dsworkbench/releases/tag/3.61) hast? (Das ist derzeit V3.61)

Solltest du wirklich die aktuelle Version haben, dann ist hätte ich gleich mal die Frage:
1) Wo hast du DS-Workbench installiert? (Es muss irgendwo sein, wo man ohne Admin rechte schreiben darfst; also unter Windows ist C:\Programme **keine** gute Idee)
2) Hast du in dem Directory wo du die Dateien hin entpackt hast vielleicht noch Daten von der Vorigen Installation? (könnte Probleme geben)

Sollte dir nichts von dem Oben helfen, so muss ich dich bitten, die Fehlermeldung hier mit Copy-Paste reinzufügen, damit ich mir ein genaueres Bild vom Problem machen kann.

**Comment by Cilko** [comment]
So sehe gerade das ich die 2.0 Version gestartet hatte, weswegen es natürlich nicht funktioniert hat. 3.61 habe ich entpackt, finde aber keine Verknüpfung oder .exe um workbench zu starten.

MfG

**Comment by extremeCrazyCoder** [comment]
Aus Windows wird DAS Workbench mit der Workbench.bat gestartet (oder mit der Launcher.bat falls kein CMD Fenster geöffnet werden soll)
Siehe Eröffnungspost im Forum (https://forum.die-staemme.de/index.php?threads/ds-workbench.80831) wobei ich jetzt nicht weiß, warum man nicht einfach einen Doppelklick auf die DSWorkbench.bat machen darf. (Das müsste eventuell noch getestet werden)

**Comment by Cilko** [comment]
Soo habe eben nochmal alle Dateien entfernt, neu entpackt und nun lässt es sich mit der Launcher.bat Datei öffnen. Vielen Dank für die schnelle Hilfe. 

MfG

**Comment by extremeCrazyCoder** [comment]
existiert hier noch ein Problem (weil das issue wieder geöffnet wurde)?
