### ISSUE TITLE
"%" Angaben bei Standardangriffen

### ISSUE THREAD

**Issue by Rewyn** [Torridity/dsworkbench#49]
Seit dem Update von 3.5 auf 3.62 ist es nicht mehr möglich Angaben in % zu machen, bei den Standardangriffen. Stattdessen bleibt das Feld einfach leer.

**Comment by extremeCrazyCoder** [comment]
Danke für die Info ich konnte es reproduzieren. Als Workaround kannst du z.B: statt 50%  Alle*50/100 schreiben

**Comment by extremeCrazyCoder** [comment]
ist erledigt
war ein Programmierfehler

Der Bugfix wird aber erst mit der nächsten Release in der offziellen Version drinnen sein. So wie es derzeit aussieht wird es aber erst nächstes Jahr wieder eine Release geben (die Änderungen die ich Plane werden viel Zeit brauchen)

**Comment by Rewyn** [comment]
Ah, danke für die Info. Soll mir reichen. :)
