### ISSUE TITLE
Frage: Standardangriffe

### ISSUE THREAD

**Issue by shoeper** [Torridity/dsworkbench#53]
Bei mir wird aktuell immer -1 Paladin eingeführt, was dann dazu führt, dass ich die Befehle nicht abschicken kann. Eigentlich eingetragen habe ich z.B. überall 0 und bei Spähern 5.

Neustarten und das anlegen einer neuen Vorlage haben das Problem nicht behoben. Jemand ne Idee?

Hab WB 3.62

**Comment by extremeCrazyCoder** [comment]
ich spiele selber auf eine Welt mit pala und hatte das Problem noch nicht.
Ich bräuchte folgende Infos um das Problem besser eingrenzen zu können:
1) Hast du die Truppen importiert (soll ja immer wieder Leute geben die glauben das braucht man nicht)
2) Versuchst du Befehle von der Befehlsübersicht oder vom Farmmanager abzuschicken
3) Falls von der Befehlsübersicht: Screenshot von deinen Standardangriffen & von dem Befehl den du abschicken willst
4) Falls vom Farmmanager: screenshots von den Einstellungen der Truppen (und der Farmen Tabelle)
5) Den Inhalt des Logfiles dazu bitte folgendes machen:
a) Altes Log File löschen (befindet sich im Ordner log)
b) WB normal starten
c) Truppen einlesen
d) im Reiter Sonstiges auf About Drücken
e) im Fenster dass sich dann öffnet auf den DEBUG button drücken
f) Einen Angriff abschicken
g) WB schließen
6) Die Welt auf der du spielst (damit ich mir mal ansehen kann ob das ein Problem mit der Welt ist)

Mit den Infos kann ich dir dann hoffentlich helfen

**Comment by shoeper** [comment]
Die Truppeninformationen waren irgendwie falsch eingelesen, so dass in den Dörfern -1 bei Paladin steht und das hat er dann anscheinend anstelle von 0 (wie in der Vorlage eingetragen) übernommen.
