### ISSUE TITLE
Version number mismatch preventing builds

### ISSUE THREAD

**Issue by tylercamp** [Torridity/dsworkbench#54]
The Core and ParserPlugin POMs need to have version numbers updated to 3.62 to match the parent POM, right now they're 3.61 and breaking the build

**Comment by extremeCrazyCoder** [comment]
I am aware of this. ich habe already fixed it inside my repro #a6e7cc3c2fe99d69b62ba02cdea23e568be0fe0f
I would not recommend you to use the latest version from my repro because it is hardly tested an so I don't know how stable it is.
