### ISSUE TITLE
Der Farm-Manager ist nicht auf No-Farm Welten verfügbar

### ISSUE THREAD

**Issue by shoeper** [Torridity/dsworkbench#62]
Kommt auf W163. Ich weiß nicht genau wie No-Farm definiert ist. In meinen Augen ist es eine Farm Welt.

**Comment by shoeper** [comment]
Mit Version 3.7

**Comment by shoeper** [comment]
Sowohl mit Oracle JDK 8 als auch mit OpenJDK 11

**Comment by ThomasJejkal** [comment]
Offenbar gibt es eine neue Unterscheidung bei den Farmeinstellungen. Einmal 'deaktiviert', dann ist der Wert in den Einstellungen '0', dann 'aktiv', dann ist er Wert '1' und zudem hab ich noch 'aktiv, mit Raubzügen' gesehen, z.B. bei besagter Welt 163. Da ist der Wert dann '3'. Im Code wird nur auf den Wert '1' geprüft, somit ist der Farmmanager inaktiv. Ich ändere es eben und in der kommenden Version funktioniert das dann wieder.

**Comment by Torridity** [comment]
Offenbar gibt es eine neue Unterscheidung bei den Farmeinstellungen. Einmal 'deaktiviert', dann ist der Wert in den Einstellungen '0', dann 'aktiv', dann ist er Wert '1' und zudem hab ich noch 'aktiv, mit Raubzügen' gesehen, z.B. bei besagter Welt 163. Da ist der Wert dann '3'. Im Code wird nur auf den Wert '1' geprüft, somit ist der Farmmanager inaktiv. Ich ändere es eben und in der kommenden Version funktioniert das dann wieder.

**Comment by shoeper** [comment]
Danke!

**Comment by godlike321** [comment]
Hey Grüße! 

Ich kenne mich leider nicht allzu gut aus, habe das oben beschriebene Problem auch.
Nun ist es ja anscheinend schon gefixt worden, ich habe mir DS Workbench dann nochmal neu geladen aber auch mit der vermeintlich neuen Version bekomme ich die Meldung "auf NoFarm Welten nicht verfügbar".
Es geht hier um Welt 167, auch mit Raubzügen. Muss ich nun noch eine Einstellung vornehmen oder evtl. sogar etwas in irgendeiner Datei ändern?
Wäre sehr dankbar für Hilfe, der Farmmanager ist einfach sooo gut, komme ohne kaum mehr zurecht  :D 

LIeben Gruß
Sam

**Comment by extremeCrazyCoder** [comment]
Damit du die Fixes bekommst musst du die aktuelle version aus dem Repro selber bauen eine offizielle Version mit den Fixes gibt es noch nicht (wenn du dir das aktuelle aus den Releases runter geladen hast).

Gerade nachgesehen auf 167 ist der Wert auch 3 und daher tritt der Bug auf.

**Comment by godlike321** [comment]
Ok danke dir, dann versuch ich mal mein Glück!
