### ISSUE TITLE
Rohstoffverteiler: Zusammenfassung nicht lesbar

### ISSUE THREAD

**Issue by shoeper** [Torridity/dsworkbench#63]
Beim Rohstoffverteiler sind mit Version 3.7 weder die Anzahl der Transporte noch die verschobenen Rohstoffe sichtbar. Mit Version 3.6 funktionierte dies problemlos.

Das Fenster breiter zu machen hilft auch nicht.

![Screenshot from 2019-05-28 14-29-12](https://user-images.githubusercontent.com/5340585/58478255-e4a91400-8155-11e9-8097-2d8e829de885.png)

**Comment by shoeper** [comment]
Sowohl mit Oracle JDK 8 als auch mit OpenJDK 11

**Comment by extremeCrazyCoder** [comment]
Mist scheint so als ob das letzte Update einige UI Probleme mit sich gebracht hat (im Farmmanager gibts dann auch noch ein Paar).

Das Problem ist, dass diese Version auf einige Libraries verzichten musste um Kompatibilität mit den neuen Java Versionen herzustellen. Das ganze schön zu fixen wird vermutlich mehrere Monate dauern (weil es eine andere Library gibt die gut aussieht, dafür müsste aber die Komplette UI de facto neu geschrieben werden)
als einzige schnelle Möglichkeit gäbe es die Standard-Size zu verändern. Ich will aber in dieser Hinsicht nix versprechen, dass das dauerhaft geht

In der Editor view sieht es wirklich knapp aus hab ihm mal bisschen mehr Größe gegeben und dass beim Vergrößern des Fensters 80% in die Tabelle gehen und 20% in diese Übersicht
Vorher:
![grafik](https://user-images.githubusercontent.com/25514433/58537188-ac0b4800-81f2-11e9-9521-24d44aa1d1de.png)
Nacher:
![grafik](https://user-images.githubusercontent.com/25514433/58537491-479cb880-81f3-11e9-9098-25249269ffba.png)
Commit: e8aae8c

**Comment by shoeper** [comment]
Ich checke das bei Gelegenheit mal aus und gucke ob es auch bei mir funktioniert.

**Comment by shoeper** [comment]
Mit dem Fix passt es wieder
