### ISSUE TITLE
High DPI Support

### ISSUE THREAD

**Issue by xystemat1c** [Torridity/dsworkbench#66]
Hello,

an option to scale the size of menu icons and text to 1.5 or 2.0 would be nice if added in future updates :smile:

**Comment by extremeCrazyCoder** [comment]
Scaling of just the menue should be possible
needs to be implemented here: https://github.com/Torridity/dsworkbench/blob/master/Core/src/main/java/de/tor/tribes/ui/RibbonLayoutConstants.java#L37
Maybe I'll change the check box into a slider in next weeks

**Comment by extremeCrazyCoder** [comment]
Implemented in beta
For testing here is a build version:
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.73-pre-2
