### ISSUE TITLE
Wachturm einzeichnen nicht möglich

### ISSUE THREAD

**Issue by TRMxDEVIL** [Torridity/dsworkbench#67]
Hallo
mit der aktuellen Version, ist es nicht mehr möglich Wachtürme zu Platzieren?
Weder mit der "Level" eingabe, noch mit dem Level 1 Werkzeug.

Die Wachtürme, sind nicht in der Wachturm Ansicht vorhanden und werden daher nicht gerendert.

Wachtürme, die durch Berichte hinzugefügt wurden, funktionieren einwandfrei

**Comment by extremeCrazyCoder** [comment]
Bei mir geht es (getestet auf dep10)

Bekommst du diese Meldung? 
![grafik](https://user-images.githubusercontent.com/25514433/66021076-a9df3000-e4e9-11e9-9a4b-437e24a8b0d8.png)

Wenn ja: auf welcher Welt spielst du?
Falls nein: wie sieht es mit Wachtürmen aus die mit der Gebäudeübersicht importiert wurden?

Ich bin gerade drauf gekommen, dass wenn ich workbench neu installiere und dann Wachtürme hinzufügen will dies ebenfalls nicht funktioniert. Sobald ich es dann aber schließe und wieder öffne geht es (und die Wachtürme die ich vorhin hinzugefügt hatte sind auch da, obwohl sie damals nicht in der Wachturmübersicht waren)
Dies gilt ebenso wenn ich ein neues Profil anlege und dann unmittelbar dannach probiere Wachtürme ein zu zeichnen.
Meinst du vielleicht das?

Weitere Fragen:
Genaue Version (du sagtest aktuelle, daher gehe ich von 3.71 aus)?

**Comment by TRMxDEVIL** [comment]
Bekomme die Meldung nicht, spiele auf 168 ist ne Wachturm Welt.

Importierte Wachtürme aus Berichten und aus der Übersicht funktionieren. Sind direkt nach dem Import da und in der Wachturmübersicht.

Ich kann nur, egal was ich versuche, keine Wachtürme manuell mit dem WachturmWerkzeug platzieren. Auch nach neustart sind die leider nicht da.

Version 3.71

**Comment by extremeCrazyCoder** [comment]
danke für die Meldung auf Welt 168 konnte ich das ganze nachstellen

mich wundert gerade etwas dass er die Wachtürme aus berichten / dem Import akzeptiert (aber das schaue ich mir jetzt noch genauer an)

Anscheinend glaubt ein Teil des codes, dass die W168 keine Wachturm welt ist...

**Comment by extremeCrazyCoder** [comment]
Nur als abschließende info:
Die Farbe kann man generell nicht bearbeiten, weil die Farbe auf der Farbe des dazugehörigen Dorfes beruht (also Spieler / Stammes Markierung)

**Comment by TRMxDEVIL** [comment]
Ok, das mit der Farbe ist gut zu wissen. Funktioniert aber auch nicht so :-P Siehe hier: 
![Map_WT_Color](https://user-images.githubusercontent.com/5021797/66116250-ae334800-e5d2-11e9-89d4-1a27fa0e53d4.png)

**Comment by extremeCrazyCoder** [comment]
Kannst du es bitte mal mit dem Probieren: https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.72 ob es da bei dir auch nicht geht?
Bei mir sieht es so aus (auf welt de168)
![Screen](https://user-images.githubusercontent.com/25514433/66116879-c8b9f100-e5d3-11e9-990e-b54d1f97496b.png)
Also es geht wieder mal. Irgendwas mach ich falsch :smile:

**Comment by extremeCrazyCoder** [comment]
ok habs nachgestellt (deinen Fehler)
es geht mit Spielermarkierungen aber nicht mit Stammesmarkierungen....

warum er bei mir die Wachtürme nicht eingezeichnet hat am Screen das muss ich noch suchen

**Comment by extremeCrazyCoder** [comment]
so dein Fehler ist gefixt
wenn dir noch was auffällt sag bitte einfach bescheid

warum er bei mir die Wachtürme manchmal nicht im Screenshot einzeichnet weiß ich nicht

**Comment by TRMxDEVIL** [comment]
Perfekt, danke dir 👍
