### ISSUE TITLE
Rechenoperatoren "Standardangriffe"

### ISSUE THREAD

**Issue by TRMxDEVIL** [Torridity/dsworkbench#69]
Hallo, 
hierbei handelt es sich nicht um einen Fehler. Höchstens in der "Hilfe".

Bei Standardangriffen gibt es die möglichkeit zu Rechnen. Unter anderem gibts es auch die < / > / = operatoren.

Nun ist meine Frage, mit was kann ich das vergleichen? 
Wenn ich nur ">1" Eintage - steht 0 im Feld.

Ich würde bei den Standardangriffen gerne eine "intelligenz" für Fakes einbauen, das er wenn zu wenig Rammen da sind, Kattas nehmen und anders rum.

Ist das so möglich oder denk ich da zu weit?

**Comment by extremeCrazyCoder** [comment]
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.72-post-1

bitte um Rückmeldung ob es funktioniert

In deinem Fall müsstest du folgendes eintragen (inklusive weg wie ich drauf gekommen bin):
Nachfolgendes ist für zuerst katas dann rammen
bh_kata=8 (BH Plätze eines Katapults korrigieren falls falsch)
bh_ramme=5 (BH Plätze einer Ramme korrigieren falls falsch)
kata=(fake-1)/bh_kata+1
kata_genug=alle_catapult>=kata
ramme_rest=(alle_catapult*bh_kata-fake-1)/bh_ramme+1
ramme=kata_genug*ramme_rest

einsetzen:
kata=(fake-1)/8+1
ramme=(alle_catapult>=((fake-1)/bh_kata+1))*((alle_catapult*8-fake-1)/5+1)

**Comment by TRMxDEVIL** [comment]
Auf 168 gibts kein Fakelimit, deswegen ist das da nicht so kompliziert mit der Formel. 
Sieht aber soweit logisch aus was da steht :-P 

Da es das Fakelimit nicht gibt hab ich nicht mit "Fake" gerechnet. 

Hab nen bissel mit den alle_(X) rumgespielt, das hat immer hingehauen. Funktioniert gut =).
Hab in der beschreibung aber nen paar Fehler gefunden.  Hier korrigiert ;).

<Property name="text" type="java.lang.String" value="&lt;html&gt;Standardangriffe sind voreingestellte Angriffe mit einer festgelegten Truppenzahl, die an vielen Stellen in DS Workbench verwendet werden k&amp;ouml;nnen. &#xa;So dienen sie z.B. dazu, die Angriffe eines Angriffsplans im Versammlungsplatz zu &amp;ouml;ffnen und die Truppen direkt einzuf&amp;uuml;gen. &#xa;Dazu m&#xfc;ssen die Truppeninformationen aus dem Spielaccount nach DS Workbench importiert werden.&#xa;Mehr dazu erf&amp;auml;hrst du in der Programmhilfe, die du mit F1 &amp;ouml;ffnest.&#xa;In den Standardangriffen k&amp;ouml;nnen verschiedene Konstanten und mathematische Rechenoperationen benutzt werden :&#xa;&lt;UL&gt;&lt;LI&gt;&lt;B&gt;+ - * /&lt;/B&gt; Die Mathematischen grundrechenoperatoren&lt;/LI&gt;&#xa;&lt;LI&gt;&lt;B&gt;^&lt;/B&gt; um eine Zahl zu Potenzieren&lt;/LI&gt;&#xa;&lt;LI&gt;&lt;B&gt;%&lt;/B&gt; der Modulo-Operator&lt;/LI&gt;&#xa;&lt;LI&gt;&lt;B&gt;alle&lt;/B&gt; entspricht der Anzahl an Truppen dieses Typs, die gerade im Dorf vorhanden sind&lt;/LI&gt;&#xa;&lt;LI&gt;&lt;B&gt;X%&lt;/B&gt; um einen prozentualen Anteil aller Truppen einzuf&#xfc;gen (z.B: &apos;50%&apos;) &#xa;&lt;LI&gt;&lt;B&gt;rnd&lt;/B&gt; eine Zufallszahl von 0 bis 1 (um z.B. bei 50% der Fakes einen spy mitzuschicken)&lt;/LI&gt;&#xa;&lt;LI&gt;&lt;B&gt;fake&lt;/B&gt; Die mindestanzahl an &lt;B&gt;BH Pl&#xe4;tzen&lt;/B&gt; die bei einem Fake abgeschickt werden m&#xfc;ssen&lt;/LI&gt;&#xa;&lt;LI&gt;&lt;B&gt;&amp;gt; &amp;lt; = &amp;gt;&amp;lt; &amp;gt;= &amp;lt;=&lt;/B&gt; Vergleichsoperatoren (1 bei ja / 0 bei nein)&lt;/LI&gt;&#xa;&lt;LI&gt;&lt;B&gt;alle_{einheitenname}&lt;/B&gt; entspricht der Anzahl an Truppen eines beliebigen Typs die gerade im Dorf vorhanden sind. &lt;br&gt;&#xa;M&#xf6;gliche Namen (sofern auf der Welt vorhanden) spear, sword, axe, archer, spy, light, marche, heavy, ram, catapult, knigh, snob, militia &lt;br&gt;&#xa;Die deutschen Namen der entsprechenden Truppen sollten genauso funktionieren&lt;/LI&gt;&#xa;&lt;/UL&gt;&#xa;Das Ergebnis wird abgerundet bevor die Truppen losgeschickt werden.&#xa; &lt;/html&gt;"/>

**Comment by extremeCrazyCoder** [comment]
Erledigt (die Anpassungen in der Hilfe) kommen mit dem nächsten offiziellen Update
