### ISSUE TITLE
html export

### ISSUE THREAD

**Issue by georgkrause** [Torridity/dsworkbench#7]
they are damaged because of missing static files:

http://www.dsworkbench.de/DSWorkbench/export/mootools.js
http://www.dsworkbench.de/DSWorkbench/export/mooRainbow.js
http://www.dsworkbench.de/DSWorkbench/export/countdown.js
http://www.dsworkbench.de/DSWorkbench/export/attack.css

**Comment by Torridity** [comment]
Fixed
