### ISSUE TITLE
Taktikplaner Angriff auf sich selber

### ISSUE THREAD

**Issue by Nerneron** [Torridity/dsworkbench#70]
Bei einem Angriffsplan auf sich selber, ist oft das Ziel- und Herkunfsdorf das selbe. Beim schicken der Angriffe wird dann "Ungültiges Ziel" angezeigt.

Wenn man das fixen würde, würde man einem das Flaggenfarmen sehr erleichtern.

**Comment by extremeCrazyCoder** [comment]
Danke für den Report
auf die Idee dass sowas gewünscht ist bin ich nicht gekommen, daher geht das auch nicht.

als Workaround würde ich dir empfehlen, dass sich die Ankunfts- und Abschick Zeiten nicht überlappen dürfen.

Würdest du einen eventuellen Fix testen? Da ich selber nicht mehr aktiv spiele kann ich das nicht wirklich testen.

Als info derzeit ist kommst du etwas spät, weil es derzeit ca 1/2 Jährlich releases gibt und die letzte vor 1 Monat war. Bis das also in einem offiziellen Build drinnen ist kann es dauern

**Comment by Nerneron** [comment]
Natürlich würde ich einen Fix testen. Ich benutze Workbench zum Flaggen farmen. D.h ich baue AGs und schicke sie dann mithilfe der Workbench auf mich selber.

**Comment by extremeCrazyCoder** [comment]
Hier sollte das jetzt behoben sein:
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.73-pre-1

**Comment by Nerneron** [comment]
Werde ich heute Abend testen :)

**Comment by Nerneron** [comment]
Funktioniert einwandfrei! Vielen Dank fürs anpassen :D
