### ISSUE TITLE
Farmmanager

### ISSUE THREAD

**Issue by xeddix** [Torridity/dsworkbench#71]
Hi, ich benutze Workbench 3.72 
kann es sein das im Farmmanager die Funktion 

**Farmen auf Adelungen und sonstige Veränderungen prüfen nicht richtig oder auch garnicht funktioniert**

gruss
edmund

**Comment by extremeCrazyCoder** [comment]
Es ist mir dazu jetzt nix bewusst. Kannst du das Problem bisschen genauer beschreiben? (Was sollte passieren?)

Es kann sein, dass es dort noch Fehler gibt :)

**Comment by xeddix** [comment]
hi, so neues problem


farmtrupp losgeschickt, das dorf war ja vom farmmanager als bb gefunden worden

inzwischen wurde das dorf aber geadelt

wenn ich jetzt den bericht einlese müsste er ja das dorf sperren,  macht er aber nicht

und wie schon vorab mal gesagt, wenn ich die dörfer auf adelungen oder veränderungen prüfen lasse erkennt er auch nichts....hat aber mal funktioniert ich weiss nur nicht mehr in welches da die letzte funktionierende version war

gruss

edmund

![Screenshot_2](https://user-images.githubusercontent.com/54592250/77329787-c46ac700-6d1e-11ea-8fb7-11e8923fb46e.jpg)

**Comment by extremeCrazyCoder** [comment]
uff hm ok
nachdem ich die Änderungen da nicht wirklich gemacht habe weiß ich jetzt natürlich auch nicht was geändert wurde und ob das einen neuen Bug erstellt hat

ich werde es mir in nächster Zeit mal ansehen

**Comment by extremeCrazyCoder** [comment]
okay ich schaue mir das gerade an
wundert mich nicht dass sich da nix sinnvolles tut, weil die einzige aktion des Knopfes ist soweit ich sehe zu sagen dass er erfolgreich geprüft hat :disappointed: 

ok habs erstmal gefixt
ich kann es aber nicht testen, weil ich den Farmmanager selber nicht benutze (und jetzt eigentlich generell nimmer aktiv spiele)
hier ist die neue Version: 
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.73-pre-2

Bitte testen und rückmelden ob es geht. Ach ja und bitte das Issue wieder öffnen, nachdem es noch nicht in master drinnen ist (also im Master branch von diesem Repository)

**Comment by xeddix** [comment]
funktioniert, super
besten dank
