### ISSUE TITLE
Zeichnungen werden nicht gespeichert

### ISSUE THREAD

**Issue by bass-ti** [Torridity/dsworkbench#72]
Moin, ich habe heute Linien (Zeichnungen) in der Weltkarte eingezeichnet. Nach einem Neustart waren die Linien alle wieder weg.

In den alten Versionen wurden diese Linien gespeichert. Ist das jetzt mit Absicht oder ein Bug?

**Comment by extremeCrazyCoder** [comment]
Also sowas sollte er sich merken :smile: 
hat er bei mir auch gerade nicht gemacht ich schau mir mal an woran es liegt

**Comment by extremeCrazyCoder** [comment]
ok habs behoben war ein klassischer copy paste fehler :)

beim abspeichern wurde das haupt element plans genannt und nicht forms
einen Fehler bei den Texten habe ich ebenfalls behoben (der Text wurde falsch abgespeichert)

**Comment by bass-ti** [comment]
super danke da kann man so schön adelskorris einzeichnen :D

**Comment by extremeCrazyCoder** [comment]
Hier ist die Release mit dem Fix:
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.73-pre-2

soweit ich es getestet habe sollte jetzt alles in Verbindung mit Zeichnungen wieder gehen

**Comment by bass-ti** [comment]
geil :)
