### ISSUE TITLE
3.72 - Laufzeiten Berechnung nach Einheitentausch falsch

### ISSUE THREAD

**Issue by TRMxDEVIL** [Torridity/dsworkbench#73]
Moin =) - mal wieder ;) 

wenn ich einen Angriff über die Karte via Drag&Drop erstelle und die Ankuftszeit ändere. Wird der Angriff mit der korrekten Zeit berechnet.
Wenn ich in der Befehlsansicht die Einheit tausche, ist die Berechnung der LZ nicht mehr korrekt.

![grafik](https://user-images.githubusercontent.com/5021797/78834786-652fd680-79ef-11ea-91cc-60c4922f7f94.png)
Das BB liegt 1 Feld (30min Ramme) weg. Nach dem ändern der Einheit zu etwas anderem und wieder zum Ursprung, tritt der Fehler auf.

Ich hab nicht getestet, das gleiche Auftritt, wenn ein Angriff über den Wizard erstellt wird. Denke aber rein logisch ja ;)

Reproduktion:
Angriff via Drag&Drop erstellen
Ankunfstzeit eingeben
Erstellen
In die Befehlsansicht wechseln
Einheit für den Inc ändern ->Zeit ändert sich nun schon falsch
Einheit zurück ändern -> Zeit ist immer noch falsch.

Ist mehrfach reprodutiert worden.

**Comment by extremeCrazyCoder** [comment]
Schaff ich jetzt irgendwie nicht zu reproduzieren (oder zumindest nicht so, als dass es von mir als Bug interpretiert wird. Höchstens als schlecht verstandenes Feature :smile: )

Ich glaube du könntest das hier meinen:
![grafik](https://user-images.githubusercontent.com/25514433/78981242-ce166c00-7b1f-11ea-9889-7fe126b13859.png)
vs
![grafik](https://user-images.githubusercontent.com/25514433/78981271-dec6e200-7b1f-11ea-9aae-24d23080f8be.png)

Hier hat workbench ein bisschen extra logik verbaut und schaut, welche die langsamste Einheit ist, die in den Eingegebenen Truppen vorkommt. Es wird dann immer diese verwendet um die Berechnung zu machen

Ich muss mir das ganze nochmal ansehen, aber auf den ersten blick ist das einstellen der Einheit ziemlich sinnlos
Was meinst du was man da machen sollte

**Comment by TRMxDEVIL** [comment]
Also ich hatte gar keine Einheiten bei der Menge eingegeben, brauchte die
workbench nur mal schnell zum gucken wann ich abschicken muss. Und dann als
Erinnerung.

Hatte nen Inc mit Adelsgeschlecht erstellt.
Habe danach über das Einheiten Bildchen auf Ramme geändert, nur um zu
gucken wir lang ich laufe.
Wenn ich dann wieder zurück auf AG gehe, ist die lz anders als vorher.

Ich glaub das hat was mit der Geschwindigkeit der Welt und den Einheiten zu
tun.

-- Was meinst du was man da machen sollte?

Wenn mind. eine Einheit gegeben ist, das Symbol automatisch auswählen und
für den Benutzer sperren. Weiß nicht wie einfach das in Java ist, bin sonst
c# coder 🤣🤣.

Am 10. April 2020 13:41:59 schrieb extremeCrazyCoder
<notifications@github.com>:

**Comment by extremeCrazyCoder** [comment]
Ich habe mir jetzt nochmal den Code, der für die Laufzeit zuständig ist angesehen und verstehe immer noch nicht warum sowas auftreten kann...
In deinem Screenshot sieht man eine Laufzeit von 31:15 für 1 Feld :roll_eyes: 
reproduzieren konnte ich es irgendwie auch nicht...

Das Einheitenfeld wird nun fürs bearbeiten gesperrt, sobald die Einheit von den Truppen festgelegt wird.

Kannst du den Fehler bitte mal mit einer neuen Installation von dieser Version reproduzieren:
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.73-pre-3

Soweit ich herausgefunden habe stammt der Screenshot von Welt 176 mit dem Account TDeV
Weiters wäre folgendes interessant:
Die Systeminformationen wenn du auf Sonstiges -> About gehst (davon Betriebsystem & Java)
Deine genaue Java version (welches Update)

Die Java version will ich 2x, weil man auch mehere Versionen von Java auf dem gleichen system installiert haben kann und dann brauche ich die genaue Version von dem Java das Workbench benutzt.

Gibt es irgendwelche Gemeinsamkeiten bei allen die diesen Fehler haben? (z.B. es verwenden alle Java 8; alle verwenden Java 13; alle verwenden Windows / Mac / Linux)

**Comment by TRMxDEVIL** [comment]
Workbench About 1/2:
![grafik](https://user-images.githubusercontent.com/5021797/79078109-68380900-7d06-11ea-8483-3225c09ddc9a.png)

Workbench About 2/2
![grafik](https://user-images.githubusercontent.com/5021797/79078152-a3d2d300-7d06-11ea-8898-3ca5f86b25c1.png)

Systemsteuerung Java
![grafik](https://user-images.githubusercontent.com/5021797/79078119-74bc6180-7d06-11ea-87bc-afa67c1419b3.png)


Account ist korret ;) 
Und mit der pre-3 kann ich das nicht mehr reproduzieren ;)

**Comment by extremeCrazyCoder** [comment]
ok ich geb jetzt erstmal auf...

Ich hab mir eine VM mit win10 und java8 update 241 aufgesetzt
die V3.72 runtergeladen
gestartet -> server176 -> account TDeV -> 2 angriffe mit dem AG Kartentool erstellt (eins zum baba unter 001 und einen zu dem rechts
LZ ist ok
Einheit verändert in der Angriffsübersicht -> die Laufzeit bleibt korrekt

Nur mal so als Frage: kannst du es mit einer neuen Installation von 3.72 reproduzieren?
Falls nicht:
bleiben die Falschen werte für die Laufzeit vorhanden wenn du workbench schließt und wieder öffnest?
hast du Discord (MKich#4434) / Skype (mkich0987) damit ich mir das ganze mal per Bildschirkmübertragung ansehen kann?

**Comment by TRMxDEVIL** [comment]
Probiere es gleich mal mit ner neuen 3.72.
Der Rechner auf dem das aufgefallen war, war übrigens frisch installiert 🤔.

Nur die WB kam über die cloud.

Discord ist vorhanden. Hab darüber zwar noch nie ne Bildschirmübertragung
gemacht, aber das bekommen wir schon hin.
Und zur Not ist ne Teamviewer Lizenz vorhanden 😅.

Nicht reproduzierbare Fehler sind immer so toll 🤣🤣

Am 13. April 2020 15:04:31 schrieb extremeCrazyCoder
<notifications@github.com>:

**Comment by extremeCrazyCoder** [comment]
Wie sieht es aus?

Das WB über die Cloud kam höre ich gar nicht gerne.
Es hilft hierbei auch nicht wenn der PC frisch installiert war
Daher kann es sein, dass bei dem was bei euch in der Cloud ist irgendwo ein Fehler in den gespeicherten Daten ist, welcher dies bewirkt

**Comment by TRMxDEVIL** [comment]
Das dacht ich mir schon. Allerdings nehm ich das nur für mich allein.
Zum syncen zwischen meinen Rechnern.

Da ist auch sichergestellt das nur ein System gleichzeitig drauf zu greift.
Außerdem ist der sync ist während die WB läuft gestoppt.

Akutell kann ich es dennoch auf keinen system außer dem Laptop reproduzieren.
Probiere das heute Abend nochmal.
Wenn ich es dann am Laptop nochmal hinbekomme, kann ich dir eine Bildschirm
aufzeichnung schicken.

Gibt's nen "debug-mode" mit erweitertem log? Dann könnte ich das auch
aktivieren und dazu legen.


Am 18. April 2020 08:48:41 schrieb extremeCrazyCoder
<notifications@github.com>:

**Comment by extremeCrazyCoder** [comment]
es gibt die DSWorkbench Debug.bat
ich denke allerdings nicht, dass dann im Log irgendwas brauchbares steht, weil selbst beim Debug nicht alle Ausgabewerte incl. wie sie entstanden sind geloggt werden
Log file (erweitert und normal) ist im Log directory. Pro starten wird ein File angelegt. Die alten werden mit gz komprimiert (es werden max 10 aufbehalten glaub ich)

**Comment by Torridity** [comment]
Sorry, dass ich mich in eure Diskussion einklinke aber nur aus Interesse. Wird dir in der Spalte "Verbleibend" ein Live Countdown angezeigt oder ist das ein (mehr oder weniger) statischer Wert? 

Hast du in den Einstellungen im Reiter "Angriffe" die Option "Angriffe in der Befehlsübersicht anzeigen" aktiv, siehst du einen Countdown. Ist das nicht der Fall, siehst du eine statische Laufzeit zum Zeitpunkt wo die Zeile das letzte Mal gezeichnet wurde. Wenn du die Einheit änderst, dann wird die Zeile neu gezeichnet, also ändert sich die Spalte "Verbleibend". Änderst du sie wieder zurück, dann wird auch die Zeile neu gezeichnet. Da aber zwischendrin Zeit vergangen ist, wird die "Verbleibend" Spalte natürlich einen anderen Wert haben.

Könnte das die Lösung des Problems sein?

**Comment by extremeCrazyCoder** [comment]
Basierend auf dem ersten Screenshot ist ebenfalls der Text in der Spalte Abshickzeit falsch, daher würde ich eher darauf tippen dass es nicht so ein Fehler ist
aber probieren kann man es mal :)

**Comment by extremeCrazyCoder** [comment]
Ist jetzt zwar schon ein bisschen her, aber kannst du bitte mal probieren ob es mit der Aktuellen beta immer noch auftritt? @TRMxDEVIL 
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.73-pre-5

hab jetzt dort es so gemacht, dass die Einheit nimmer geändert werden kann, wenn sie durch die Truppen festgelegt ist

**Comment by TRMxDEVIL** [comment]
@extremeCrazyCoder  sry für die Ultra späte Antwort... Hatte viel zu tun. Und nutze schon länger die pre-5 kann den Fehler nicht mehr reproduzieren.
Close war also richtig und kann wieder gemacht werden. Wollte nur was dazu sagen ;)
