### ISSUE TITLE
invalid END header

### ISSUE THREAD

**Issue by alex-d13** [Torridity/dsworkbench#74]
Hi ich bekomme fehler beim mvn install assembly:assembly:

[INFO] Compiling 458 source files to /home/alex/Documents/temp/dsworkbench/Core/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: error reading /home/alex/.m2/repository/flamingo/flamingo/1.0/flamingo-1.0.jar; invalid END header (bad central directory offset)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Skipping DSWorkbench
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for DSWorkbench 3.73:
[INFO] 
[INFO] DSWorkbench ........................................ SUCCESS [ 10.718 s]
[INFO] Core ............................................... FAILURE [  2.033 s]
[INFO] ParserPlugin ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.152 s
[INFO] Finished at: 2020-05-04T10:36:36+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project Core: Compilation failure
[ERROR] error: error reading /home/alex/.m2/repository/flamingo/flamingo/1.0/flamingo-1.0.jar; invalid END header (bad central directory offset)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :Core

habe den .m2 folder schon einmal komplett gelöscht, brachte nichts.

mvn -v
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-51-generic", arch: "amd64", family: "unix"

java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

Hat jemand eine Idee woran das liegen kann?

**Comment by extremeCrazyCoder** [comment]
eventuell kannst du mal probieren das directory /home/alex/.m2 zu löschen
bei mir tritt der fehler nicht auf. Es könnte sein, dass bei dir beim download was schief gelaufen ist (alles was in .m2 drinnen ist wird aus dem Internet runter geladen)

sag bitte bescheid ob das hilft wenn nicht schau ichs mir genauer an

**Comment by Pippo8291** [comment]
Ich bekomme den gleichen Fehler: 

error: error reading /home/alex/.m2/repository/flamingo/flamingo/1.0/flamingo-1.0.jar; invalid END header (bad central directory offset)

**Comment by extremeCrazyCoder** [comment]
ok ich hab mir das jetzt mal genauer angesehn
erstmal sorry an den ersten, dass ich überlesen hab dass er den .m2 ordner bereits gelöscht hat

die problematische lib kommt aus diesem repro: https://github.com/Torridity/dsworkbench/commit/61eb74a9481c879c81782eea36e637219b330665
Damit kann es sein, dass bei mir etwas schief gegangen ist
nachdem ich selber noch nie probiert hab das ganze neu zu clonen ist mir das nicht aufgefallen

Ich hab das original file mit dem von jetzt verglichen und die md5summen sind unterschiedlich
das hier ist das korrekte file:
https://github.com/Torridity/dsworkbench/blob/5099143f23c6da157f0e296c88c3b850ba046b31/lib/flamingo/flamingo/1.0/flamingo-1.0.jar

das derzeitige File im repro müsst ihr mit diesem ersetzen. Anschließend müsst ihr noch das falsche File aus .m2/repository/flamingo/... raus löschen
dann sollte es kompillieren

sorry da ich bei mir das m2 repro nicht lösche hab ich immer die version im cache benutzt und es ist mir nicht aufgefallen
