### ISSUE TITLE
Workbench connectet nichtmehr zum Server

### ISSUE THREAD

**Issue by Apfelwisser** [Torridity/dsworkbench#75]
Hi,
vom einen auf den anderen Tag connected die WB nichtmehr zum Server [https://prnt.sc/sc5qm2](url) .
Idk, Java ist aktuell, ich hab die WB neu runtergeladen, Resettet etc, nichts hilft. Auch kein Antivir oder ähnliches, nutze nur den Windefender, auch deaktiviert. Bin ratlos :(
Gruß Jan

**Comment by extremeCrazyCoder** [comment]
erstmal windefender deaktivieren: naja bin mir nicht sicher ob das ne so gute idee ist :D
stell mal bitte das log file aus dem logs ordner rein
eventuell hast du dort eine Exception die mir hilft den Fehler zu finden

**Comment by Apfelwisser** [comment]
[dsworkbench.log](https://github.com/Torridity/dsworkbench/files/4589950/dsworkbench.log)


hm ist ja wieder an ;D das müsste der File sein, wäre cool wenn du was findest!

**Comment by Apfelwisser** [comment]
i dont really know, heute gehts wieder totally fine, ich glaube ich würde sterben als Programmierer :D

**Comment by extremeCrazyCoder** [comment]
Sorry das ich erst jetzt Antworte
hab das vorhin am Handy gesehen und dann vergessen zu Antworten

Im Log steht nur "Connection Timeout"
Ich weiß jetzt nicht wirklich warum sowas auftritt, normalerweise hätte ich gesagt dass du zu dem Zeitpunkt nicht mit dem Internet verbunden warst, aber ich gehe davon aus dass das Internet funktioniert hat, weil du sonst workbench nicht neu runterladen hättest können??

Freut mich zwar zu hören dass es jetzt wieder geht, allerdings hilft das auch nicht wirklich :D
