### ISSUE TITLE
Zeitenauswahl im Taktikplaner

### ISSUE THREAD

**Issue by TheisNiklas** [Torridity/dsworkbench#82]
Im Taktikplaner ist es nicht möglich einen Zeitbereich über 0 Uhr auszuwählen.
Vermute das liegt daran, dass die Zeitleiste aktuell bis 24 Uhr geht, was dann als 0 Uhr am Folgetag gilt.
Dadurch wird eine Wahl vom Folgetag ab 0 Uhr blockiert.
Möglicherweise dann einfach die Auswahl als Endzeitpunkt auf 23:59:59 begrenzen.

**Comment by extremeCrazyCoder** [comment]
ich verstehe jetzt das Problem nicht
Möglichkeiten:
- Du versuchst einen Täglichen Zeitspann zu machen: Dann entspricht der Folgetag dem heutigen und du kannst wenn du z.B. von 22 Uhr bis 4 Uhr machen willst 2 Zeitspannen machen einen mit 22 bis 24 und einen mit 0 bis 4
- Du versuchts das für eienn Tag zu machen dann machst du zuerst einen von 22 bis 24 Uhr und anschließend für den Folgetag einen von 0 bis 4 Uhr

Was meinst du mit die Auswahl begrenzen?
Wenn du eien Zeitspann von 1 bis 2 Uhr machst dann geht der effektiv von 1:00:00:000 bis 1:59:59:999



Ich denke ich hab jetzt eine Idee was du meinst:
Es gab mal einen Bug wo der Zeitspann bis 2:00:00:000 ging das sollte aber bereits gefixt sein mit b7f5c504faf18ac22ad3c48e8ea55d66fb9343e5
also ab [3.73-pre-8](https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.73-pre-8)
welche Version nutzt du?

**Comment by TheisNiklas** [comment]
Bisher hatte ich die Version 3.73-pre-9, habe aber gerade nochmal auf die aktuellste pre-25 geupdatet.

Es geht bei dem Problem um Punkt 2 deiner aufgeführten Möglichkeiten.
Wenn ich ein Zeitfenster zum Beispiel am 20.10. von 21h bis 24h einstelle, erscheint als Text bei den Zeitfenstern:
![grafik](https://user-images.githubusercontent.com/39201560/96564106-05ca5180-12c3-11eb-87b3-e110b3601b6d.png)
Versuche ich dann ein Zeitfenster am 21.10. von 0h bis 2h einzurichten, kommt diese Meldung (Unten sieht man auch was ich versucht habe einzurichten):
![grafik](https://user-images.githubusercontent.com/39201560/96564257-3611f000-12c3-11eb-8c3e-005cffc13425.png)

Daher meinte ich, dass beim ersten Eintrag das Zeitfenster in den Folgetag gerutscht ist und vl auf 23:59:59 begrenzt werden sollte.

**Comment by extremeCrazyCoder** [comment]
Ups mein letzter fix war anscheinend nicht ausreichend......
https://github.com/extremeCrazyCoder/dsworkbench/releases/tag/3.73-pre-26
habs jetzt nochmal gefixt wenn du noch was findest sag bescheid :)

**Comment by TheisNiklas** [comment]
Top, vielen Dank!
Funktioniert jetzt einwandfrei.

Wenn ich noch was finde meld ich mich.
